const fs=require('fs'),vm=require('vm'),assert=require('assert/strict'),path=require('path'),tree=require('./dom_tree.cjs');
const root=path.resolve(__dirname,'..'),crypto=require('crypto').webcrypto;
const storage=()=>{const map=new Map();return {getItem:k=>map.get(k)||null,setItem:(k,v)=>map.set(k,String(v)),removeItem:k=>map.delete(k)}};
const tick=()=>new Promise(r=>setTimeout(r,5));
(async()=>{
 const d=tree(fs.readFileSync(path.join(root,'index.html'),'utf8'));d.querySelector('#integrationsView').classList.add('active');
 const profile=d.createElement('div');profile.id='sharedProfilePanel';d.body.appendChild(profile);
 const seed=JSON.parse(fs.readFileSync(path.join(root,'server/seed.json'))),user=seed.users.find(u=>u.id==='u1');let periods=[],calls=[];
 const context={console,document:d,URL,URLSearchParams,AbortController,Uint8Array,crypto,FormData:d.FormData,sessionStorage:storage(),history:{replaceState(){}},location:{origin:'http://localhost:8000',search:'',assign(url){calls.push(['navigate',url])}},setInterval:fn=>periods.push(fn),setTimeout,clearTimeout,confirm:()=>true,Event:class{},open:()=>{},KaziorCRM:{currentUser:()=>user,people:()=>seed.users,aiContext:()=>({}),toast(){},openDocuments(){},acceptLogin(){},api:async(path,data)=>{calls.push([path,data]);if(path==='/api/whatsapp/status')return {channels:seed.users.map(u=>({id:u.login,engineerId:u.id,phone:u.phone,idInstance:'test-instance',hasToken:true,enabled:false,routing:'engineer'}))};if(path==='/api/oauth/providers')return {links:[],publicOrigin:'http://localhost:8000',providers:['google','yandex','mailru','microsoft'].map(id=>({id,redirectUri:'http://localhost:8000/api/oauth/callback/'+id,ready:false}))};if(path==='/api/integrations/status')return {telegram:{message:'test',linked:0,recent:[]},ai:{enabled:false},eds:{enabled:false}};return {ok:true,restartRequired:false}}}};context.window=context;vm.createContext(context);
 vm.runInContext(fs.readFileSync(path.join(root,'v16-ui.js'),'utf8'),context);vm.runInContext(fs.readFileSync(path.join(root,'v17-ui.js'),'utf8'),context);await d.fire('DOMContentLoaded');periods.forEach(fn=>fn());await tick();
 assert.equal(d.querySelectorAll('[data-oauth-config]').length,4);assert.equal(d.querySelector('[data-integration="whatsapp"]').elements.id.children.length,7);assert.equal(d.querySelector('[data-integration="eds"]').elements.provider.value,'ncanode');
 const form=d.querySelector('[data-oauth-config="google"]');form.elements.client_id.value='test-client';form.elements.client_secret.value='test-secret';await form.onsubmit({preventDefault(){}});assert(calls.some(([p,v])=>p==='/api/integrations/configure'&&v.provider==='google'&&v.client_secret==='test-secret'));assert.equal(form.elements.client_secret.value,'');
 d.querySelector('#edsLoginBtn').click();assert(d.querySelector('#edsChooser'));assert(d.querySelector('[data-key]'));d.querySelector('#edsChooser').querySelector('[data-close]').click();assert(!d.querySelector('#edsChooser'));
 assert(d.querySelector('#ticketCategory').closest('label').classList.contains('ticket-category'));assert(d.querySelector('#mailNavBtn'));
 const mailDoc=tree(fs.readFileSync(path.join(root,'mail.html'),'utf8'));const mailContext={...context,document:mailDoc,FormData:mailDoc.FormData,fetch:async(url,opt)=>({ok:true,json:async()=>url==='/api/state'?{user}:{accounts:[],messages:[]}}),setInterval:()=>{},sessionStorage:storage()};mailContext.window=mailContext;vm.createContext(mailContext);vm.runInContext(fs.readFileSync(path.join(root,'mail.js'),'utf8'),mailContext);await tick();assert.equal(mailDoc.querySelector('#mailUser').textContent,user.name);mailDoc.querySelector('[data-connect="yandex"]').click();assert(mailDoc.querySelector('#mailDialog').open);assert.equal(mailDoc.querySelector('#mailDialog').querySelector('[name="password"]').type,'password');
 console.log('PASS: v17 settings, four OAuth forms, seven WhatsApp channels, EDS chooser/cancel, employee category, mail page/connect dialog');
})().catch(e=>{console.error(e);process.exitCode=1});
